defaults: &defaults

  # Active OAuth2 provider.
  OAUTH2_SIGN_IN_PROVIDER: ~

  # Configuration variables for sign in with Barong OAuth2 server.
  # See https://github.com/rubykube/omniauth-barong
  #
  # Barong uses Doorkeeper under the hood so you can refer to it's docs any time.
  # See more information at https://github.com/doorkeeper-gem/doorkeeper/wiki/Testing-your-provider-with-OAuth2-gem
  BARONG_CLIENT_ID:           ~
  BARONG_CLIENT_SECRET:       ~
  BARONG_DOMAIN:              ~
  BARONG_OAUTH2_REDIRECT_URL: ~ # Specify URL address to which user will be redirected after successful sign in.

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
