default: &default
  adapter:    mysql2
  encoding:   utf8
  collation:  utf8_general_ci
  pool:       5
  host:       <%= ENV.fetch('DATABASE_HOST', '127.0.0.1') %>
  username:   <%= ENV.fetch('DATABASE_USER', 'root') %>
  password:   <%= ENV.fetch('DATABASE_PASSWORD', '') %>

development:
  <<: *default
  database: applogic_development

test:
  <<: *default
  database: applogic_test

production:
  <<: *default
  url:      <%= ENV['DATABASE_URL'] %>
  pool:     10
  database: <%= ENV.fetch('DATABASE_NAME', 'applogic_production') %>
